### ISSUE TITLE
Dishook v0.2.0

### ISSUE THREAD

**Issue by juanpisuribe13** [juanpisuribe13/Dishook#5]
## Known issues
- [x] Typo with -m flag in edit command
- [x] Dishook returns an error when no argument is detected; **should return the commands list instead**. (as said on #6)
- [x] #7
- [x] #8
- [x] #9

## TODO
- [x] just clean up the garbage code lo.
- [x] Change versioning scheme.
- [x] Fix known issues.
- [x] Implement execute code (which is a mirror of the root code, or maybe make it viceversa), just to avoid confusion in the help section to improve UX. (#6)

**Comment by juanpisuribe13** [comment]
note to myself in the future: next time do a pull request for these things
